### ISSUE TITLE
libdb5.3++-dev required instead of libdb4.8++-dev

### ISSUE THREAD

**Issue by mawaway** [slimcoin-project/Slimcoin#11]
The readme states that libdb4.8++-dev is required to build, but building with libdb4.8++-dev results in a runaway exception with the wallet and the daemon refuses to build. Installing libdb5.3++-dev fixes this. I built slimcoin on linux.

**Comment by mawaway** [comment]
I do not believe this is a database forward compatibility issue, as I have deleted all ~/.slimcoin files and the wallet gives an 11DbException.

**Comment by ghost** [comment]
There are other considerations that need to be taken into account ... https://github.com/bitcoin/bitcoin/issues/3686#issuecomment-74836708
