### ISSUE TITLE
0.4.1 - Block submitting error

### ISSUE THREAD

**Issue by d5000** [slimcoin-project/Slimcoin#4]
_johnnylatte_ reported the following bug at Reddit and Bitcointalk:

> https://bitcointalk.org/index.php?topic=1141676.msg12404053#msg12404053
> 
> Mining on version 0.4.1 compiled myself on ubuntu 14.04 32 bit I get the following error when a block is submitted:
> 
>  HTTP request failed: The requested URL returned error: 500 Internal Server Error [2015-09-13 08:49:02] submit_upstream_work json_rpc_call failed
> 
> I have received this error consistently when submitting blocks to version 0.4.1.
> 
> To verify it wasn’t just caused by my modified version of slimminer I also mined on version 0.3.2.0 > found at https://github.com/kryptoslab/slimcoin/releases compiled from source on the same machine. I have found several blocks that have been submitted and accepted without a problem.

I confirm that until now, I couldn't find any blocks with 0.4.1 - that may be related to this issue.

**Comment by ghost** [comment]
Fixed in commit: 209d107
